# Site settings
title: Fala Candidato
email: sela-roinuj@hotmail.com
description: "Fala Candidato é um agregador de vídeos das propagandas eleitorais gratuitas de televisão e que tem como intuito ajudar o eleitor a comparar as propostas e escutar o que os candidatos a Presidência da República tem a dizer."
baseurl: "/falacandidato"
url: "http://junior-ales.github.io"
twitter_username: junior_ales
github_username:  junior-ales

# Build settings
markdown: kramdown
permalink: pretty
exclude: ["Gemfile", "Gemfile.lock", "README.md", "deploy.sh"]
